feat: Frontend map utils
EKK-Ingarden/LandsatWebTracker pull request #42
Opened 2024-09-27 17:41 UTC by Norbiros

2024-09-27 18:54 UTC, goteusz-maszyk commented
Imagine using leaflet
https://maplibre.org/

2024-09-27 19:23 UTC, Norbiros commented
How using maplibre I can eaisly draw a polygon, display overlay image/layer, draw point etc?

2024-09-27 19:49 UTC, wikipop commented
Test image display with [this](https://planetarycomputer.microsoft.com/api/data/v1/item/preview.png?collection=landsat-c2-l2&item=LC09_L2SP_182046_20240920_02_T1&assets=red&assets=green&assets=blue&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55&format=png) before merging

2024-09-27 19:51 UTC, wikipop requested changes

2024-09-27 19:51 UTC, wikipop commented on frontend/pages/map.client.vue
> +  url: "https://www.printablee.com/postpic/2011/06/blank-100-square-grid-paper_405041.jpg",
does it work with geocoded images? Read my other comment.

2024-09-28 19:17 UTC, wikipop approved these changes

2024-09-28 19:19 UTC, merged